### ISSUE TITLE
Is the API down ?

### ISSUE THREAD

**Issue by ParagRaut** [TheDiscordians/discordians.js#2]
I tried to connect to the api 
I got following 
![B3B4F433-7EB5-4A44-BB8B-B1AAE4BFDE2B](https://user-images.githubusercontent.com/16030809/82822294-d34c3200-9ea5-11ea-8a80-d51bc4fa50b6.jpeg)

Is the API down on heroku?

**Comment by bsantosh909** [comment]
@ParagRaut Really sorry we missed out on your issue, but yeah the API has been closed.

Because we have preety much closed the service as of now. But if you are really upto using the API service I can share the source code in coming days :D

**Comment by ParagRaut** [comment]
Well that's nice of you, but as the necessity is mother of invention, I actually made my own API which fetches various comic strips for my blazor webassembly project
Check it out here: https://paragraut.github.io/ComicsAppWasm/

**Comment by bsantosh909** [comment]
That looks great, and we are really sorry if you were relying on this project..

We were completely unaware if anyone was realying on it, and since this project was eating some of the free dyno hours over at github (_because of which another project was dying_), the decision was made to remove this project from heroku..

**Comment by ParagRaut** [comment]
It's okay @TheLearneer but yes Indeed my project was relying on it but now it's self sufficient :)

**Comment by bsantosh909** [comment]
If you ever feel like the need of the source or any features that were in the API, just let me know...

**Comment by ParagRaut** [comment]
sure you can mail me, or even better you can have it on your own github. I'll clone it from there

**Comment by bsantosh909** [comment]
@ParagRaut The original repository that was powering the API is live on the git url: https://github.com/TheLearneer/discordians-api 
Originally it was closed source, but I have inclined way towards open source projects now and your comment made it realized it was still closed source...

So now it is open source, you can fork it and host over at heroku for identical behaviour like earlier!

**Comment by ParagRaut** [comment]
Thank you very much and kudos for the good decision. I’ll check it out
